[package]
name = "build-expression"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "build-expression"
path = "main.rs"

[dependencies]
common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }