# Protocol configuration for Bundle Generator
# This file contains protocol addresses and parameters across multiple chains

protocols:
  aave:
    v3:
      polygon:
        pool: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
        oracle: "0xb023e699F5a33916Ea823A16485e259257cA8Bd1"
        flash_loan_fee: 0.0009  # 0.09%
      
      arbitrum:
        pool: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
        oracle: "0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7"
        flash_loan_fee: 0.0009

  uniswap:
    v2:
      polygon:
        pool: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"  # QuickSwap
        flash_loan_fee: 0.003  # 0.3% swap fee
      
      arbitrum:
        pool: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"  # SushiSwap
        flash_loan_fee: 0.003

  compound:
    v3:
      polygon:
        pool: "0xF25212E676D1F7F89Cd72fFEe66158f541246445"
        flash_loan_fee: 0.0  # No flash loan fee on Compound V3
      
      arbitrum:
        pool: "0xA5EDBDD9646f8dFF606d7448e414884C7d905dCA"
        flash_loan_fee: 0.0