[package]
name = "parse-and-validate"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parse-and-validate"
path = "main.rs"

[dependencies]
common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }