name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Lean via elan
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- --default-toolchain nightly --no-modify-path --yes
          echo "::add-path::$HOME/.elan/bin"
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build maths library
        working-directory: maths
        run: |
          lake update
          lake build 